### ISSUE TITLE
Crash to desktop with v1.2.18 and MystCraft 0.11.2.01

### ISSUE THREAD

**Issue by Arrabal-** [lawremi/CustomOreGen#64] opened 2015-03-31 16:05 UTC
Getting a crash to desktop during world profiling on an existing world using the latest MystCraft release (0.11.2.01).

Crash report:  http://pastebin.com/QKgRfZ7q

From the crash report it looks like it is due to interactions between Mystcraft, and Custom Ore Generation.  Crash report indicates that MystCraft, FastCraft, ATG, and Custom Ore Generation all could be involved.  Had all of these mods working together with the following versions:

MystCraft 0.11.0.00
FastCraft 1.19
ATG 0.11.0
Custom Ore Generation 1.2.18

Tried updated version of the above mods and also removed them one at a time (and tried different combinations of mods).  Validated that MystCraft 0.11.2.01 works with:

FastCraft 1.19 & 1.21
ATG 0.11.0 & 0.12.0

MystCraft 0.11.2.01 and Custom Ore Generation 1.2.18 result in crash.  Removing Custom Ore Generation resolves crash issue.  Not sure if this is on the MystCraft side or the Custom Ore Generation Side so I am reporting to both

**Comment by Arrabal-** [comment] 2015-03-31 20:15
Per the request of XCompWiz I have provided the links to other issue posts as well as some additional detail and the fml client logs.

https://github.com/XCompWiz/Mystcraft-Issues/issues/57
https://github.com/lawremi/PerFabricaAdAstra/issues/45

Also, I did some further testing and reproduced the crash with minimal mods installed.  The installed mods are:

FastCraft 1.21
MystCraft 0.11.2.01
ATG 0.12.0
COG 1.2.18
Per Fabrica Ad Astra (PFAA) 0.2.23

PFAA adds a heavily customized ore generation configuration to COG and adds new ores, along with replacing all the vanilla stone and ore.  The crash only occurs when both COG and PFAA are installed with MystCraft 0.11.2.01.

Here are the log files, as requested (had to split into two pastebins to get around the size limit.  Part 1 goes through preInit):

Part 1:  http://pastebin.com/pwezyGZb
Part 2:  http://pastebin.com/dzskLKT9

**Comment by lawremi** [comment] 2015-03-31 20:30
COG uses a deferred generation algorithm that can cause issues with certain mod configurations. Rather than populate a chunk upon the initial request, COG waits until all chunks within a certain radius of that chunk have had a population request. Once that happens, it populates. The rationale is that ore gen can cross chunk boundaries, and COG aims to remove/replace ore gen using its substitution distributions after it knows that there is no possibility of such "spill over" occurring. There is no easy way (that I can find) to know whether a chunk has been generated before (this has to work across saves), and the check that I am using somehow (with certain mod configurations) stimulates additional world generation, and thus infinite recursion.

Right now, the only work-around is to change the deferredPopulationRange (under debug settings) to 0, and disable all unwanted ore generation in mod configs (otherwise, some will slip through).

**Comment by XCompWiz** [comment] 2015-03-31 23:49
I don't see infinite recursion in that error.  I see a NullPointerException.  Specifically at CustomOreGen.Integration.ATG.ATGIntegration.getSurfaceHeight(ATGIntegration.java:14).

This doesn't look like it has anything at all to do with recursion.

Is it possible that ATGBiomes.getGeneratorInfo(world, x, z) returns null, so the [0] part causes a NPE?

**Comment by lawremi** [comment] 2015-04-01 01:11
My bad. I should have actually looked at the crash log, but I was hurrying at work. There was a different bug reported elsewhere with a very similar mod configuration. Yes, that must be what is causing the error. According to the docs, null should not be returned there, so I would bring this issue up with the ATG maintainer.

**Comment by XCompWiz** [comment] 2015-04-01 10:14
Where do you see this documentation?  Is it javadoc?
While I could just send CUTS a message, where should we post the actual bug report?

**Comment by lawremi** [comment] 2015-04-01 12:03
Yea, it's Javadoc. I sent him a message via the forum, and linked to this issue, which I think should suffice to document the problem for now, even though it is not entirely specific.

**Comment by TTFTCUTS** [comment] 2015-04-01 15:46
Well, it *can* return null but really shouldn't if the world being checked for is an ATG world... there's a point here though where if someone tries to get the info for an ATG world which isn't dim 0 it'd return null, which I need to fix. Not that I know how it COULD be not dim 0.

```java
	@SubscribeEvent
	public void onGeneratorInfoEvent( ATGGeneratorInfoEvent event ) {
		int x = (int) Math.round(event.x);
		int z = (int) Math.round(event.z);
		
		if (ATG.isATG(event.world)) {

			ATGChunkManager m = (ATGChunkManager)(event.world.getWorldChunkManager());
			
			double height = m.getRawHeightDouble(x,z);
			double temp = m.getRawTempDouble(x,z);
			double moisture = m.getRawMoistureDouble(x,z);
			
			event.info = new double[] { height, temp, moisture };
		}
	}
```

Where ATG.isATG is
```java
	public static boolean isATG(World world) {
		return world.provider.terrainType.getWorldTypeName() == "ATG" && world.provider.dimensionId == 0;
	}
```

Which should probably be changed to match the API one which doesn't check the dimension...

If it's not being caused by that mismatch somehow, I'm not really sure why it'd ever return null.

**Comment by lawremi** [comment] 2015-04-01 15:56
Is it possible that Mystcraft is delegating to ATG world generation in alternate dimensions? Is there any strict reason why ATG cannot generate outside of the overworld?

**Comment by XCompWiz** [comment] 2015-04-01 20:07
Mystcraft should be using it's own world generation stuff.  That said, it's asking for the terrain type, and I think Mystcraft might just report whatever terrain type the save says it is...  It used to be save global, not dimension specific.  I don't know.

**Comment by lawremi** [comment] 2015-04-02 05:30
So you're saying it's possible that Mystcraft always reports the overworld terrain type? Some COG configs expect Mystcraft to borrow information from the overworld. Could Mystcraft instead return the default overworld information, or whatever is most appropriate?

**Comment by lawremi** [comment] 2015-04-02 11:52
Please ignore the message I sent when half asleep ;) I guess it is up to the `WorldProvider` as to which `terrainType` it uses (`WorldProvider.terrainType`), but the `terrainType` is irrelevant to most implementations, so they simply inherit the overworld/save setting. So I guess MystCraft could set whatever it wants there, like "Myst" or something, but it sounds like you have a (justified) reluctance to change that behavior?

**Comment by XCompWiz** [comment] 2015-04-02 14:25
I'm all for setting it to a custom terrain type. I just don't know if anyone uses it as a save-level setting.
I could force Mystcraft to always use an Overworld-like terrain type (the normal default). it would solve both ways.
It comes back to "is there a way to check save-level settings outside of asking the current world object?"  if there is, then I can do whatever with the Mystcraft provider's terrainType and tell people to go that route.  If there isn't...  maybe we should make a Forge PR...

**Comment by lawremi** [comment] 2015-04-03 11:53
There is `World.worldInfo.terrainType`. Yes, it belongs to the `World` object, but it can be different from `World.provider.terrainType`, and it looks like most of the `WorldInfo` fields are save-level (seed, name, version, etc). So I think you can tell them to go that route.

**Comment by XCompWiz** [comment] 2015-04-06 22:14
Not everything in WorldInfo is save-level, though, like the current time can wander dim to dim.
Bot otherwise, yes, I think this is a good solution for this field.
Any suggestions on what I should change it to?  How I should handle it?

**Comment by lawremi** [comment] 2015-04-06 23:46
I was thinking you would just set it to "Myst" or something...

**Comment by XCompWiz** [comment] 2015-04-07 17:51
That question was more for TTFCUTS. :P

**Comment by XCompWiz** [comment] 2015-04-14 22:50
Sat down to look at how to handle this, and I've decided just to use the "DEFAULT" world type.
Two reasons:
1) There can only be 16 world types in the game, due to how Minecraft implements this (ARG WHY?)
2) The constructors are private, so it's not possible to make a WorldType without reflection... This is just annoying.

The first one is the main reason. Were it just the second I'd still make my own type.
Anyway, this should fix it for the next build.

**Comment by lawremi** [comment] 2015-04-15 03:34
Great, thanks a lot, XCompWiz. Closing...

**Closed by lawremi** 2015-04-15 03:34 UTC
