### ISSUE TITLE
Deadlock with strategic cloud generation

### ISSUE THREAD

**Issue by LemADEC** [lawremi/CustomOreGen#152] opened 2016-08-01 20:41 UTC
Using CustomOreGen-1.7.10-1.2.24, on a Forge dedicated server, world generation gets stuck in a deadlock in some chunks:
![image](https://cloud.githubusercontent.com/assets/4776032/17307939/cc8a3bd2-5837-11e6-8223-62e0ac4699e7.png)

I've been able to narrow it down to this settings:

```
<VeinsPreset name='PresetHintVeins'>
    <Description>
        Single blocks, generously scattered through all heights (density is about that of vanilla iron ore).
        They will replace dirt and sandstone (but not grass or sand), so they can be found nearer
        to the surface than most ores.  Intened to be used as a child distribution for large, rare strategic
        deposits that would otherwise be very difficult to find.
        Note that the frequency is multiplied by ground level to maintain a constant density, but not by
        ore frequency because it is assumed that the frequency of the parent distribution will already
        be scaled by that.
    </Description>
    <Setting name='MotherlodeFrequency' avg=':= 80 * dimension.groundLevel/64' range=':= 30 * dimension.groundLevel/64'/>
    <Setting name='MotherlodeSize' avg='0.6' range='0'/>
    <Setting name='MotherlodeHeight' avg=':= 50/64 * dimension.groundLevel' range=':= 46/64 * dimension.groundLevel'/>
    <Setting name='MotherlodeRangeLimit' avg=':= 45 * oreSize' range=':= 30 * oreSize' type='uniform'/>
    <Setting name='BranchFrequency' avg='0' range='0'/>
    <Setting name='OreDensity' avg='1' range='0'/>
    <Setting name='OreRadiusMult' avg='1.0' range='0'/>
    <Replaces block='stone'/>
    <Biome name='.*'/>
</VeinsPreset>

<CloudPreset name='PresetStrategicCloud'>
    <Description>
        Large irregular clouds filled lightly with ore.  These are huge, spanning several
        adjacent chunks, and consequently rather rare.  They contain a sizeable amount of
        ore, but it takes some time and effort to mine due to low density.
        The intent for strategic clouds is that the player will need to actively search for
        one and then set up a semi-permanent mining base and spend some time actually mining
        the ore.
    </Description>
    <Setting name='DistributionFrequency' avg=':= 0.001 * oreFreq'/>
    <Setting name='ParentRangeLimit' avg='32' range='32' type='normal'/>
    <Setting name='CloudRadius' avg=':= 25 * oreSize' range=':= 10 * oreSize'/>
    <Setting name='CloudThickness' avg=':= 14 * oreSize' range=':= 6 * oreSize'/>
    <Setting name='CloudSizeNoise' avg='0.2'/>
    <Setting name='CloudHeight' avg='32' range='16' type='normal' scaleTo='sealevel'/>
    <Setting name='CloudInclination' avg='0' range='0.35'/>
    <Setting name='OreRadiusMult' avg='1' range='0.1'/>
    <Setting name='OreDensity' avg='0.1'/>
    <Setting name='OreVolumeNoiseCutoff' avg='0.5'/>
    <Replaces block='stone'/>
   <Biome name='.*'/>
</CloudPreset>

<Cloud name='ClayCloud' block='minecraft:clay' inherits='PresetStrategicCloud'>
    <Description>
        Diffuse coal cloud surrounded by single-block "hint" veins, found in swamps.
    </Description>
    <DrawWireframe>:=vnlaDrawWireframes</DrawWireframe>
    <WireframeColor>0x60404050</WireframeColor>
    <Setting name='DistributionFrequency' avg=':= 40 * _default_'/>
    <Setting name='CloudHeight' avg=':= 48/32 * _default_' range=':= 12/16 * _default_'/>
    <Setting name='CloudRadius' avg=':= 0.8 * _default_' range=':= 0.8 * _default_'/>
    <Setting name='CloudThickness' avg=':= 0.2 * _default_' range=':= 0.15 * _default_'/>
    <Setting name='OreDensity' avg=':= 1.6 * _default_'/>
    <Veins name='ClayHintVeins' block='minecraft:clay' inherits='PresetHintVeins'>
        <DrawWireframe>:=vnlaDrawWireframes</DrawWireframe>
        <WireframeColor>0x60404080</WireframeColor>
        <Setting name='MotherlodeFrequency' avg=':= 1.2 * _default_' range=':= _default_'/>
        <Setting name='MotherlodeRangeLimit' avg=':= 0.1 * _default_' range=':= 0.1 * _default_'/>
    </Veins>
</Cloud>
```

If I comment the 'ClayCloud', then reload the configuration, world generation works fine.
After that, if I restore the 'ClayCloud', doing a /cogPopulate 20 in that area doesn't reproduce the issue for some obscure reason.

Seed is 3282764633197385895 with Biome'O'Plenty generator, in the WarpDrive space dimension
Coordinates are 2963 246 -117

**Comment by lawremi** [comment] 2016-10-31 12:51
Pretty sure this is a duplicate of #147 and closely related to #146, so closing this one. We need to cleanup the bezier spline interpolation stuff (happening here in the hint veins).

**Closed by lawremi** 2016-10-31 12:51 UTC
