### ISSUE TITLE
Crash at 2nd Worldgen in Options Menu

### ISSUE THREAD

**Issue by BenjKl** [lawremi/CustomOreGen#178] opened 2016-12-11 17:38 UTC
Minecraft crashes every 2nd time a new world is created when the Options Menu of CustomOreGen is openend.
1. I create a world
2. Open CustomOreGen Options Menu
3. Start world
4. Save and Quit to Title
5. Create new World
6. Open Option Menu -> Crash

java.lang.NullPointerException: Updating screen events
	at CustomOreGen.Server.GuiCustomOreGenSettings.func_73866_w_(GuiCustomOreGenSettings.java:103)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:495)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:965)
	at CustomOreGen.Server.GuiCustomOreGenSettings$GuiOpenMenuButton.func_146116_c(GuiCustomOreGenSettings.java:791)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:408)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by lawremi** [comment] 2016-12-12 12:12
Almost surely a duplicate of #163, although this has a nice reproducible example.

**Closed** 2016-12-12 12:19 UTC
