### ISSUE TITLE
Mod conflict with MUON

### ISSUE THREAD

**Issue by Claycorp** [lawremi/CustomOreGen#194] opened 2017-05-18 16:47 UTC
MUON modifies village generation with a fair amount of changes, but for some reason if you install MUON and COG it breaks MUON. So instead of getting nice villages that have buildings and farms you get pancakes. See MinimumContent/muon#3 I know it's not your job to fix it but any input would be appreciated. Thanks!

**Comment by Scratchman** [comment] 2017-05-18 23:46
I can confirm this, I've tested with both mods enabled and get broken flattened villages but disabling either mod allows for normal village creation.

http://imgur.com/a/UuD4S

I'd really like to be able to use both mods because of how broken vanilla minecraft villages can be.

**Comment by lawremi** [comment] 2017-05-19 12:25
Not sure what's happening here. The "holes" in the village generation do not seem to overlap any of COG's distributions, although disabling all of COG's generation does fix it. It sounds like MUON makes pretty deep (core mod) changes to structure generation, which COG uses for most of its distributions, so it could be violating one of COG's assumptions somewhere. I think the MUON author will need to look into this. I'm closing this to keep the discussion in the other issue.

**Closed by lawremi** 2017-05-19 12:25 UTC
