### ISSUE TITLE
Nether: No Ore generation

### ISSUE THREAD

**Issue by walkerjonny** [lawremi/CustomOreGen#112] opened 2015-11-24 01:34 UTC
Hi, 
I'm using the newest COG 1.2.24.
I have both NetherOres and NetherRocks in my mod list and both configuration tabs show up when I try to generate a new world.
However, for some reason COG doesn't generate any of those ores in the Nether. Only ores that aren't generated through COG are generated in the Nether.
Do you have any idea about what could have happened and how I could possibly fix this if the error lies on my side?
Here are the COG files from my world.
[CustomOreGen_Options(Main).txt](https://github.com/lawremi/CustomOreGen/files/42266/CustomOreGen_Options.Main.txt)
[CustomOreGen_Options(Nether).txt](https://github.com/lawremi/CustomOreGen/files/42269/CustomOreGen_Options.Nether.txt)

**Comment by lawremi** [comment] 2015-11-24 02:34
Please check with debugging wireframes turned on (see the cogdocs wiki). Are the distributions showing up, but not populating?

**Comment by walkerjonny** [comment] 2015-11-24 11:26
I'll check it when I'm back from work. It will take about 8 to 10 hours from now.

**Comment by walkerjonny** [comment] 2015-11-25 03:09
Sorry, I'm doing something wrong and cannot see what.
First, I'm playing SP only.
On world creatio I have turned on Debugging Mode in the COG settings.
I have tried the command "/cogEnableDebugging enable" and I got only "Error: null"
When I try to use another command I'm getting only "You do not have permission to use this command".

What I have recogniced is that in the config file for the dimension -1 the value "COGActive" is set to false by default. I have changed that to true and I also have deleted all region files for dimension -1. 
But this changed nothing about the ore generation issue in the Nether unfortunately. The mod ores still do not generate.

**Comment by reteo** [comment] 2015-11-25 04:52
Did you create the game in creative mode?

Debug mode only takes commands when you start the game in creative mode.  Starting in survival and switching to creative doesn't work.

**Comment by lawremi** [comment] 2015-11-25 12:17
You can start the game in any mode, but you have to start the server and enable cheats. Then you can do `/cogEnableDebugging`.

**Comment by walkerjonny** [comment] 2015-11-25 12:33
I tried both "/cogEnableDebugging" and "/cogEnableDebugging enable" but got both times "Error: null".

@lawremi 
What do you mean with "you have to start the server"? In SP the server module starts when you load a world. Are you referring to an own server instance of Minecraft?

@reteo 
I'll try that out when I'm back at home in about 6 to 8 hours.

**Comment by lawremi** [comment] 2015-11-25 12:42
Sorry, I meant "Open to LAN".

**Comment by walkerjonny** [comment] 2015-11-25 12:44
I'll check that out, too.

**Comment by walkerjonny** [comment] 2015-11-25 21:48
@reteo 
Didn't work for me. I am still getting both "Error: null" and "You do not have permission to use this command" when I start the new world in creative mode.

 @lawremi 
Found that option after googeling for it. Doesn't work for me either unfortunately... I'm still getting the same messages.
I'll remove some mods from my list for testing purposes. Maybe it will work then. I'll report back after some testing which will take a while...

**Comment by reteo** [comment] 2015-11-25 22:03
Error:NULL usually appears when Custom Ore Generation is not running; this suggests that it crashed while making the world.  What mod tabs show up along the top of the COG setup screen?

**Comment by walkerjonny** [comment] 2015-11-26 03:33
I did some testing now.
COG works fine in the overworld by the way.
The mod that causes those command issues is Factorization. 
Possibly it causes also the ore generation issue within the Nether but I'm not sure about that at the moment.
One question: In the nether there are many distributions looking like a barrel but they do not contain any ores. They contain only nether rack. Should that be that way?

**Comment by reteo** [comment] 2015-11-26 03:57
What version of Custom Ore Generation are you using?

**Comment by walkerjonny** [comment] 2015-11-26 10:27
@reteo 
Those screenshots are with Factorization included, right?
I had an issue a few day before when I added COG 1.2.24 and I replaced the complete COG config folder because COG didn't show anything in the configuration setup.
Because I deactivated ore generation within nearly all other mods I used the actual Sprocket at the last weekend to add "Substitiute:no" to all the advanced ore ini files (default section) and generated new XML-Files from them using sprocket-advanced.py.  I replaced the existing ini files with my own ones.
But as I remember I had troubles with two of the newly generated XML files because they caused COG not to work anymore. Because of that I used the original ones from the modules\default folder of COG and removed the ore wiping section manually. After doing that the COG Setup window was working fine.
However, it might be possible that I used some old XML files for some mods that I had created by myself about two month before using sprocket because those mods aren't included in COG itself.
I will make sure to recreate the XML files for them with the newest sprocket.
I will also try out the original Factorization.xml that comes with COG 1.2.24.

**Comment by reteo** [comment] 2015-11-26 12:33
Actually, those changes were accidentally committed before Custom Ore Generation was ready; if you use the XML or INI files containing stone (chisel, project red, geostrata, etc.) from the current Sprocket github, then the game is not going to work, because the configuration assumes the presence of a new preset (presetStratum) in CustomOreGen_Config.xml that's only present in the unreleased version of COG.

I'd undo that commit, but to be honest, I'm not sure how.

**Comment by walkerjonny** [comment] 2015-11-26 13:13
If the CustomOreGen_Config_Default.xml is all I need I'm fine with that.
It might also not be a big problem for me to download the actual COG repository and to compile it for my own use if you recommend that. 
And yes, I think chisel was one of the mods that caused the troubles with the new XML Files.
But I'm also using Project Red and TinkersSteelworks.

By the way after checking the CustomOreGen_Config_Default.xml above, should the Project Red  and the Biomes o' Plenty XML Files then not be placed in the first group together with the other stone related mod XML Files? As I remember it both are distributing some larger stone or granite deposits.

**Comment by reteo** [comment] 2015-11-26 13:21
I just finished removing the stratafied configurations, so now you should be able to use Sprocket's configs without changing anything.

**Comment by walkerjonny** [comment] 2015-11-26 15:41
OK, thank you!
I'll use the updated sprocket then and report back.

**Comment by walkerjonny** [comment] 2015-11-27 10:08
@reteo 
I had some issues with the Chisel2.xml that is generated through the sprocket-advanced.py. Because I have turned off ore/stone generation within the chisel config file I used then the chisel2.xml that is shipped with COG 1.2.24 and removed the "Substitution" part manually (also did the proper changes within the COG config file and placed that file into the "custom" folder). That worked fine.

Factorization works also fine now.

But unfortunately I have troubles now with GregTech 5.09.10. 
I'm using the default files that are shipped with COG and placed GregTech at the end of the ore generation queue within the COG config file to assure that it is processed at last as recommended. The GregTech section in the COG setup window pops up properly and I can set the required settings. But when the world is loaded the COG commands do not work anymore and I don't see the wireframes. Without GregTech they do and the wireframe show up as expected.
Is there a known interaction or configuration option that has to be set to make GregTech and COG work together? Possibly I'm making a mistake within the COG setup window.

**Comment by lawremi** [comment] 2015-11-27 11:07
Please look in the log for error messages. I guess you removed the chisel substitution for performance reasons. It might make sense for Sprocket to add an option for that.

**Comment by walkerjonny** [comment] 2015-11-27 12:31
You're right about chisel. Sprocket has a substitution option already which works fine for all other mods. Unfortunately something messes up when it generates the XML file for chisel out of the ini.

I did also check the Minecraft log for COG related errors. The attached file contains them. Maybe you can help me with this.
[log_errors.txt](https://github.com/lawremi/CustomOreGen/files/45702/log_errors.txt)

**Comment by lawremi** [comment] 2015-11-27 12:47
Well, that's Gregtech 6, but you're using GT5. Are you changing any GT options from the default?

**Comment by walkerjonny** [comment] 2015-11-27 12:54
I have just renewed the Gregtech_results.txt, so check it out.
And yes, i don't want Gregtech to replace vanilla ores so I deactivated that option.
I also wanted to have clay deposits so I activated that option

**Comment by lawremi** [comment] 2015-11-27 13:12
There is a file called CustomOreGen_Options.txt in your world save directory. Would you mind posting that somewhere? Thanks.

**Comment by reteo** [comment] 2015-11-27 13:12
Which Sprocket are you using?  The original or advanced?  I'm afraid I haven't been maintaining the original, as all my work has been focused on the advanced version.

**Comment by walkerjonny** [comment] 2015-11-27 13:47
@reteo
I'm using the advanced version normally. And Chisel is in the advanced version. That is why I'm wondering.
See the chisel.zip download link.
http://www.file-upload.net/download-11075996/chisel.zip.html

Below there is a zip file with my whole COG configuration. I have changed some parts to my needs but it should not be too complicated to understand.
Especially i have created a folder called "customspecial" and added there some files that I wanted to move to beginning or ending of the ore generation queue. The COG config file reflects that. 
I haven't changed the GregTech.XML. I just copied it from the default folder.  
http://www.file-upload.net/download-11075997/CustomOreGen.zip.html

**Comment by walkerjonny** [comment] 2015-11-27 14:08
Just tried with COG set to default settings but there are still the same issues with Gregtech.

**Comment by reteo** [comment] 2015-11-27 15:39
Hmmm... "NBT specified, but matching block tile.gravel:0 lacks tile entity"

Looks like the problem is with the Gregtech config.

I don't use NBT data with my configurations, so this is outside my experience... and Gregtech (both versions), Extra Caves, and Dartcraft are the only configurations I have not completely remade.

**Comment by walkerjonny** [comment] 2015-11-27 16:31
Very strange:
I did an additional wipe and tried a minimal setup with Gregtech - that worked.
Now I'm expanding that setup and adding in my own config files one by one to see when the troubles begins. I'll report back.

**Comment by walkerjonny** [comment] 2015-11-28 01:20
@reteo 
When you do the ore removal part in the sprocket-advanced.py of sprocket I suggest to do it that way:
Check first if the ore exist before you try to replace it. Example:
"<IfCondition condition=':= ?blockExists("mod:ore")'> <Replaces block='mod:ore' weight='1.0' /> </IfCondition>"
This is like the XML files, that are shipped with COG, are set up usually.
Don't do only "<Replaces block='mod:ore' weight='1.0' />". 
That could lead to issues when that block doesn't exist but the mod does. 

I'm also quite sure that the setting "Substitute: no" does not work. I compared some XML files I created with those that are in the Advanced\XML folder and the ore removal part is still there. It looks exactly the same. 
Normally the "<Replaces block='mod:ore' weight='1.0' />" lines should be either disabled or not be there if "Substitute: no" is set. 
You can compare them by downloading my COG configuration above. Then you'll see it by yourself. 
You can also have a look at my sprocket-master copy.
http://www.file-upload.net/download-11077625/Sprocket-master_26.11.2015.zip.html
I left the XML files that I created together with the modified INI files in the Advanced\INI folder.

**Comment by reteo** [comment] 2015-11-28 04:38
I originally did that.  In fact, it was a request by @lawremi that I not do it that way.  The current method works much better and is less likely to crash the mod.

As for your substitution issue, keep in mind that "Substitute" is a command for the original Sprocket.  Sprocket Advanced replaces "Substitute" with "Main Block Cleanup" (default is "yes") and "Alternate Block Cleanup" (default is "no").

**Comment by walkerjonny** [comment] 2015-11-28 13:08
@reteo 
Thank you very much for that detailed explanation! That explains a lot.
I had just overseen the "Sprocket Advanced Options.md".
Had to read some parts two times until I got it but that is not your fault. You explained it well there. 
So the "Main Block Cleanup" setting is used then to replace all existing blocks usually.
I'll check that out and report back.

**Comment by walkerjonny** [comment] 2015-11-28 14:29
@reteo 
There seems to be one left issue. Maybe that will be fixed when the next COG version will be released.
I just have tried to add a second block (minecraft:gravel) to the Replaces list:
"Replaces: minecraft:stone, minecraft:gravel"
That causes that COG does not work then properly anymore if I add the newly generated XML file to the custom modules list.
Only when I set it to "Replaces: minecraft:stone" it works fine.
Am I right with the assumption that this will work with the next release of COG?

**Comment by reteo** [comment] 2015-11-28 17:06
If you add a module to the custom modules folder, and it is a modified version of a default module, you need to comment out or delete the line in CustomOreGen_Config.xml that loads the default module.

**Comment by walkerjonny** [comment] 2015-11-29 19:49
Just a question about the CustomOreGen_Options.txt in the dimension folders:
Should they only contain the ores COG should distribute in that dimension or should they contain all ores COG distributes in any dimension?

**Comment by reteo** [comment] 2015-11-29 20:26
I honestly don't know anything about dimension folders; I just make overall configurations.

**Comment by walkerjonny** [comment] 2015-11-29 23:25
But maybe lawremi does.
@lawremi 
Could you possibly answer my question, please?

**Comment by lawremi** [comment] 2015-11-29 23:45
The options within a dimension directory are only considered for that dimension. If the option is not used by the config in that dimension, then it does not need to be defined.

**Comment by walkerjonny** [comment] 2015-11-30 01:05
Then the CustomOreGen_Options.txt should only contain the ores for the dimension it is placed in, right?
Because actually the CustomOreGen_Options.txt in my DIM-1 (Nether) folder contains all ores which irritates me. I thought it should only contain the ores for the nether.

**Comment by lawremi** [comment] 2015-11-30 01:09
It doesn't hurt anything, but yea, I guess the config would ideally avoid defining the options when they are not relevant.

**Comment by walkerjonny** [comment] 2015-11-30 20:23
@reteo 
I tried to use the VanillaMinecraft.xml from your actual sprocket (advanced\XML)
Beside Gregtech it was the only XML file for COG to handle.
I got this error and COG refused to work:
![minecraft_logs_latest log - notepad](https://cloud.githubusercontent.com/assets/6742581/11483400/72434d3a-97a8-11e5-9dc1-f84a6a25aa7c.png)
I didn't change anything within that XML file.

**Comment by reteo** [comment] 2015-11-30 20:57
The problem has to be one of the Gregtech configs, seeing as the error explicitly lists a mismatch between tile.gravel:0 and some NBT thing.  None of my configurations make use of NBT data, because I wouldn't know how to acquire that information... and the Gregtech configs are so extremely custom that I'm afraid to touch them.

Maybe @lawremi might know how to fix this problem, because I'm pretty much stumped.

**Comment by lawremi** [comment] 2015-11-30 21:14
Assuming that the GT config is not completely broken, it would help to have precise instructions on how to reproduce this issue. I don't think it's happening "out of the box".

**Comment by walkerjonny** [comment] 2015-11-30 22:04
The error above and the error below only happen with your XML files.
When I use the files that are shipped with COG everything works fine.

This one happened with Factorization.xml from your actual sprocket.
This error quite the same, just a little additional issue cones in addition: "SparseVeins" is replaced with "LayeredVeins".
![minecraft_logs_latest log - notepad _factorization](https://cloud.githubusercontent.com/assets/6742581/11486007/b0a6a2b2-97b6-11e5-8987-4a69351e0bc7.png)

**Comment by walkerjonny** [comment] 2015-11-30 22:44
@reteo 
There is a third one, this time with TinkersConstruct.xml.
Here the related log error:
![minecraft_logs_latest log - notepad _tinkersconstruct](https://cloud.githubusercontent.com/assets/6742581/11486928/57249310-97bc-11e5-997f-11a9e39f271d.png)

**Comment by reteo** [comment] 2015-11-30 22:46
So, when you got those error messages, was Gregtech installed?

**Comment by walkerjonny** [comment] 2015-11-30 23:05
For the errors above - yes.

But now i have removed all other XML files except TinkersConstruct.xml (had to edit the main COG config file for this as the Gregtech XML files had an required import. Changed that to optionalimport).
The error remains:
![minecraft_logs_latest log - notepad tinkersconstruct-only](https://cloud.githubusercontent.com/assets/6742581/11487405/31a0d876-97bf-11e5-919c-774127d1214c.png)

**Comment by reteo** [comment] 2015-11-30 23:09
Hmmm... AH, by disabling the default configs, you now have the Gregtech config running first.

In the config file, I have two entries for Gregtech; one is just after the default list, and a second one is commented out after the custom entries.  What happens if you comment out the first, and uncomment the second?

**Comment by walkerjonny** [comment] 2015-11-30 23:18
@reteo 
No.
As I said I have removed ALL other XML files except TinkersConstruct.xml. That includes both Gregtech XML files.

**Comment by walkerjonny** [comment] 2015-11-30 23:25
The relevant part of my CustomOreGen_Config looks that way at the moment:
![customoregen_config xml](https://cloud.githubusercontent.com/assets/6742581/11487770/ee5955a4-97c1-11e5-852b-b17cfea10e8f.png)
Everything else is commented out.

**Comment by reteo** [comment] 2015-11-30 23:31
Okay.  That clarifies that.

Now, back to my original question: What happens when you remove the Gregtech _jar_ file from the mods directory?  Does the error still happen?

**Comment by walkerjonny** [comment] 2015-11-30 23:32
@lawremi 
A question about Gregtech:
As I have seen the actual Gregtech distributions are quite rare. Is that really planned that way?

@reteo 
I'll repot back in about 15 minutes.

**Comment by walkerjonny** [comment] 2015-12-01 00:09
@reteo @lawremi 
That is really interesting: Without Gregtech in my mod folder the error above dissapears and COG works fine with the TinkersConstruct.xml from the actual sprocket.

**Comment by lawremi** [comment] 2015-12-01 00:45
Is COG breaking for you "out of the box" with Gregtech and TCon installed? Or are you customizing something?

**Comment by walkerjonny** [comment] 2015-12-01 01:19
I did all the last tests with files out of the "sprocket" box TinkersConstruct related. 
I didn't touch the Gregtech XML files as they are really complicated and quite hard to understand. So they are out of the box from COG.
However, when I use the TinkersConstruct or the other mods XML files that are out of the Box from COG and modify them manually to my needs (mostly removing the ore removal part as I disable ore generation in the mod configs) they work well.

**Comment by lawremi** [comment] 2015-12-01 01:25
So this is some weird interaction between a TinkersConstruct XML generated by Sprocket (is there an exact link to the file?) and Gregtech?

**Comment by reteo** [comment] 2015-12-01 01:26
You can find all the configs [here](https://github.com/reteo/Sprocket/tree/master/configs/Advanced/XML).

**Comment by walkerjonny** [comment] 2015-12-01 01:33
What I have noticed is that the main difference between the sprocket files and the cog files seems to be the missing check if a block or an ore exists before replacing it.
sprocket:
![sprocket-tinkersconstruct](https://cloud.githubusercontent.com/assets/6742581/11489850/40d0de4a-97d3-11e5-9e95-3607fb972629.png)
COG:
![cog-tinkersconstruct](https://cloud.githubusercontent.com/assets/6742581/11489859/52ce19a0-97d3-11e5-8b3c-93b754787a68.png)
Could it be possible somehow that those missing checks could be the reason?
Also, what happens if a mod drops one ore at a later time that is distributed normally through COG in an existing world when those checks do not occur?

**Comment by lawremi** [comment] 2015-12-01 01:36
`Replaces` should not care whether a block exists. It looks like the configs are now using `ReplacesOre` for gravel where they weren't before. Is that safe? Gravel is not a registered ore in vanilla. Maybe a mod registers it, but it does not seem safe in general. Same applies to dirt.

**Comment by reteo** [comment] 2015-12-01 01:51
Hmmm... NEI had shown those oredict values, so I had assumed they were correct.  If they're not, I'll go ahead and remove the relevant code from Sprocket.

**Comment by reteo** [comment] 2015-12-01 01:52
Before I finalize, is sand a registered oredict or no?

**Comment by lawremi** [comment] 2015-12-01 01:53
It depends on the loaded mods. Plain forge registers stone and sand but not dirt and gravel.

**Comment by reteo** [comment] 2015-12-01 01:53
Okay.  Sand and stone.  Removing dirt and gravel from Sprocket's oredict replacement and regenerating the oregen for both COG and Sprocket.

**Comment by walkerjonny** [comment] 2015-12-01 01:55
What is the difference between "Replaces" and "ReplacesOre"? 
Does "ReplacesOre" use ore dictionary support? That might be interesting when used to replace different stones with ores.
And how differs "Replaces" from "ReplacesOre" when it comes to performance?

@reteo 
OK. I'll test that tomorrow if I see that you have changed your sprocket repository.

**Comment by reteo** [comment] 2015-12-01 01:56
Sprocket is now updated.

**Comment by walkerjonny** [comment] 2015-12-01 01:56
Sorry the first part don't need to be answered anymore..

**Comment by walkerjonny** [comment] 2015-12-02 12:20
@reteo 
Although the xml files still contain "ReplacesOre Block='dirt'" or "ReplacesOre Block='gravel'" they are working now. That is the god point.

[TinkersConstruct.xml.txt](https://github.com/lawremi/CustomOreGen/files/49698/TinkersConstruct.xml.txt)
See lines 649 and 652 as example.
Shouldn't there be "Replaces block" instead of "ReplacesOre block" for dirt and gravel? 
It is a bit irritating. However, it works now.

**Comment by reteo** [comment] 2015-12-02 13:26
Ah, forgot about that code.  It should only come into play if you use strategic clouds; the hint vein code was separate from the rest.

**Comment by reteo** [comment] 2015-12-02 13:27
I'll get to fixing that as soon as I'm capable.

**Comment by reteo** [comment] 2015-12-03 00:59
Okay, the Hint Veins have now been updated on the Sprocket and Custom Ore Generation trees.  All traces of "ReplaceOre" for dirt and gravel should now be gone.

**Comment by lawremi** [comment] 2015-12-03 02:47
I'm going to close this, even though I have no clue why this ore dict issue affected NBT matching in a separate config...

**Closed by lawremi** 2015-12-03 02:47 UTC

**Comment by walkerjonny** [comment] 2015-12-03 12:01
@reteo 
You did this without editing the sprocket-advanced.py?
Because I just created a modified XML file (Main Block Cleanup: no) and I still have "ReplacesOre" for dirt and gravel...
[AppliedEnergistics.xml.txt](https://github.com/lawremi/CustomOreGen/files/50753/AppliedEnergistics.xml.txt)
See lines 215 and 218 for example.

**Comment by reteo** [comment] 2015-12-03 15:11
Woops.  I forgot to commit the sprocket-advanced.py script along with all the configs.  It's now uploaded.

**Comment by walkerjonny** [comment] 2015-12-03 15:28
Thank you!
I'll check that out when I'm back at home.

**Comment by walkerjonny** [comment] 2015-12-03 18:48
So, sprocket-advanced.py works fine now.
Now you need just to do the same with the classic sprocket.py *grin* ;-)

**Comment by reteo** [comment] 2015-12-03 19:46
The classic one will eventually be overhauled; I will be removing the advanced options, and replacing them with Y-low, Y-high, vanilla veins per chunk, and ores per vanilla vein, and then use the program to calculate the correct values for the various distributions.

That should be enough to allow a good set of defaults for people who just want to play the mod, while more advanced configuration writers will have all the tools they need with Sprocket Advanced.

**Comment by walkerjonny** [comment] 2015-12-04 03:57
With the hint about sprocket classic I referred to the "ReplacesOre" for dirt and gravel.
That happens there, too. 
Would be good if you might fix it.
About the planned changes: Sounds nice! 
Sprocket classic is indeed a bit complicated if you just want to set some basic settings for ore distributions.
