### ISSUE TITLE
Rare crash after travelling world

### ISSUE THREAD

**Issue by asiekierka** [lawremi/CustomOreGen#62] opened 2015-03-07 08:45 UTC
http://asie.pl/cog-crash.txt (with FastCraft)

http://asie.pl/cog-crash-no-fastcraft.txt (without FastCraft)

**Comment by asiekierka** [comment] 2015-03-27 19:11
URLs fixed.

**Comment by lawremi** [comment] 2015-03-28 00:35
Temporary workaround is to set the deferred population range to zero, under the debugging options. The downside is that the removal of mod ore generation will not be complete. Of course, you can simply disable the generation in the mod's config to avoid that issue.

**Comment by lawremi** [comment] 2016-10-31 12:11
Not able to reproduce, so closing.

**Closed by lawremi** 2016-10-31 12:11 UTC
